name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
        
      - name: Build JAR
        run: mvn -B package
      
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: docsource-jar
          path: target/docsource-*.jar
        
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.0.0.2'
          java-version: '17'
          components: 'native-image'

      - name: Build Linux
        run: mvn -B -Pnative package

      - name: Upload Linux
        uses: actions/upload-artifact@v3
        with:
          name: docsource-linux
          path: target/docsource

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.0.0.2'
          java-version: '17'
          components: 'native-image'

      - name: Build Windows
        run: mvn -B -Pnative package

      - name: Upload Windows
        uses: actions/upload-artifact@v3
        with:
          name: docsource-windows
          path: target/docsource.exe
