name: Build Docker Base Image

on:
  workflow_dispatch:
    inputs:
      linux-version:
        description: 'Linux image version'
        required: false
      jar-version:
        description: 'Java image version'
        required: false

jobs:
  build-linux-base-image:
    name: Build Linux base image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event.inputs.linux-version != ''
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker build
        run: |
          docker build . -f .docker/Dockerfile -t docker.io/loicgreffier/docsource-base:${{ github.event.inputs.linux-version }}
          docker push docker.io/loicgreffier/docsource-base:${{ github.event.inputs.linux-version }}
  
  build-jar-base-image:
    Name: Build JAR Base Image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event.inputs.jar-version != ''
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker build
        run: |
          docker build . -f .docker/jar.Dockerfile -t docker.io/loicgreffier/docsource-base:${{ github.event.inputs.jar-version }}-jar
          docker push docker.io/loicgreffier/docsource-base:${{ github.event.inputs.jar-version }}-jar