name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-jar:
    name: Release JAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: mvn clean package -DskipTests

      - name: Metadata
        id: metadata
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          LATEST_VERSION=$(git tag -l --sort=-version:refname | head -1 | cut -d 'v' -f 2)
          echo current_version=$(echo $CURRENT_VERSION) >> $GITHUB_OUTPUT
          echo is_latest_version=$(echo $(test "$LATEST_VERSION" == "$CURRENT_VERSION" && echo true || echo false)) >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docsource-jar
          path: target/docsource-${{ steps.metadata.outputs.current_version }}.jar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .docker/jar.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            loicgreffier/docsource:${{ steps.metadata.outputs.current_version }}-jar
            ${{ steps.metadata.outputs.is_latest_version == 'true' && 'loicgreffier/docsource:latest-jar' || '' }}
        env:
          DOCKER_BUILD_SUMMARY: false

      - name: Generate release changelog
        uses: mikepenz/release-changelog-builder-action@v5
        id: build_changelog
        with:
          configuration: changelog-builder.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          artifacts: target/docsource.jar
          draft: true
          prerelease: true
          allowUpdates: true

  build-native:
    name: Build Native Image ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    outputs:
      current_version: ${{ steps.metadata.outputs.current_version }}
      is_latest_version: ${{ steps.metadata.outputs.is_latest_version }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'ubuntu-24.04-arm', 'windows-latest', 'macos-latest' ]
        include:
          - os: 'ubuntu-latest'
            platform: 'linux-amd64'
            extension: ''
          - os: 'ubuntu-24.04-arm'
            platform: 'linux-arm64'
            extension: ''
          - os: 'macos-latest'
            platform: 'darwin-arm64'
            extension: ''
          - os: 'windows-latest'
            platform: 'windows-amd64'
            extension: '.exe'
    steps:
      - name: Checkout project
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '21'
          native-image-musl: ${{ matrix.os == 'ubuntu-latest' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: mvn clean package -DskipTests -Pnative ${{ matrix.os == 'ubuntu-latest' && '-Pnative-static-musl' || '' }}

      - name: Metadata
        id: metadata
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          LATEST_VERSION=$(git tag -l --sort=-version:refname | head -1 | cut -d 'v' -f 2)
          echo current_version=$(echo $CURRENT_VERSION) >> $GITHUB_OUTPUT
          echo is_latest_version=$(echo $(test "$LATEST_VERSION" == "$CURRENT_VERSION" && echo true || echo false)) >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docsource-${{ matrix.platform }}
          path: target/docsource-${{ steps.metadata.outputs.current_version }}${{ matrix.extension }}

  release-native:
    name: Release Native Image
    runs-on: ubuntu-latest
    needs: build-native
    steps:
      - name: Checkout project
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          pattern: docsource-*
          path: target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            loicgreffier/docsource:${{ needs.build-native.outputs.current_version }}
            ${{ needs.build-native.outputs.is_latest_version == 'true' && 'loicgreffier/docsource:latest' || '' }}
        env:
          DOCKER_BUILD_SUMMARY: false

      - name: Generate release changelog
        uses: mikepenz/release-changelog-builder-action@v5
        id: build_changelog
        with:
          configuration: changelog-builder.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename file
        run: mv target/docsource-*/docsource-${{ needs.build-native.outputs.current_version }}${{ matrix.extension }} target/docsource-*/docsource-${{ needs.build-native.outputs.current_version }}-${{ matrix.platform }}${{ matrix.extension }}

      - name: Update release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          artifacts: target/docsource-*/docsource-${{ needs.build-native.outputs.current_version }}-${{ matrix.platform }}${{ matrix.extension }}
          draft: true
          prerelease: true
          allowUpdates: true